// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optica1.Models;

#nullable disable

namespace Optica1.Migrations.Proyectooptica
{
    [DbContext(typeof(ProyectoopticaContext))]
    [Migration("20251201174046_AddCamposHistoriaClinica")]
    partial class AddCamposHistoriaClinica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Optica1.Models.Citas", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_cita");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int?>("IdHistoriaclinica")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_historiaclinica");

                    b.Property<int?>("IdUsuarioempleado")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuarioempleado");

                    b.Property<int?>("IdUsuariopaciente")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuariopaciente");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.HasKey("IdCita")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarioempleado" }, "fk_c_idusuarioempleado_idx");

                    b.HasIndex(new[] { "IdUsuariopaciente" }, "fk_c_idusuariopaciente_idx");

                    b.ToTable("cita", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_compra");

                    b.Property<DateOnly?>("FechaCompra")
                        .HasColumnType("date")
                        .HasColumnName("fecha_compra");

                    b.HasKey("IdCompra")
                        .HasName("PRIMARY");

                    b.ToTable("compra", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Diagnostico", b =>
                {
                    b.Property<int>("IdDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_diagnostico");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("FechaEdicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_edicion");

                    b.Property<int?>("IdHistoriaclinica")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_historiaclinica");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDiagnostico")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdHistoriaclinica" }, "fk_d_idhistoriaclinica_idx");

                    b.ToTable("diagnostico", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Historiaclinica", b =>
                {
                    b.Property<int>("IdHistoriaclinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_historiaclinica");

                    b.Property<string>("AgudezaVisualOd")
                        .HasColumnType("longtext");

                    b.Property<string>("AgudezaVisualOi")
                        .HasColumnType("longtext");

                    b.Property<string>("Antecedentes")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int?>("IdUsuarioOptometra")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioPaciente")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("RxFinalOd")
                        .HasColumnType("longtext");

                    b.Property<string>("RxFinalOi")
                        .HasColumnType("longtext");

                    b.HasKey("IdHistoriaclinica")
                        .HasName("PRIMARY");

                    b.ToTable("historiaclinica", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.MedioDePago", b =>
                {
                    b.Property<int>("IdMedioDePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_medio_de_pago");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdMedioDePago")
                        .HasName("PRIMARY");

                    b.ToTable("medio_de_pago", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_perfil");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdPerfil")
                        .HasName("PRIMARY");

                    b.ToTable("perfil", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Persona", b =>
                {
                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id_persona");

                    b.Property<string>("Correo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("segundo_nombre");

                    b.Property<long?>("Telefono")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona")
                        .HasName("PRIMARY");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_producto");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaActualizacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<int?>("IdProveedorNit")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedor_nit");

                    b.Property<string>("Marca")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("marca");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.Property<float?>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock");

                    b.Property<int?>("StockMinimo")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Tipo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("tipo");

                    b.HasKey("IdProducto")
                        .HasName("PRIMARY");

                    b.HasIndex("IdProveedorNit");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.ProductoCompra", b =>
                {
                    b.Property<int>("IdProductocompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_productocompra");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_compra");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_producto");

                    b.HasKey("IdProductocompra")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCompra" }, "fk_pc_idcompra_idx");

                    b.HasIndex(new[] { "IdProducto" }, "fk_pc_idproducto_idx");

                    b.ToTable("producto_compra", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.ProductoVentum", b =>
                {
                    b.Property<int>("IdProductoventa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_productoventa");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_venta");

                    b.HasKey("IdProductoventa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProducto" }, "fk_pv_idproducto_idx");

                    b.HasIndex(new[] { "IdVenta" }, "fk_pv_idventa_idx");

                    b.ToTable("producto_venta", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedorNit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedor_nit");

                    b.Property<string>("Correo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.Property<long?>("Telefono")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedorNit")
                        .HasName("PRIMARY");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.ProveedorCompra", b =>
                {
                    b.Property<int>("IdProveedorcompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedorcompra");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_compra");

                    b.Property<int?>("IdProveedorNit")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_proveedor_nit");

                    b.HasKey("IdProveedorcompra")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCompra" }, "fk_pc_idcompra_idx")
                        .HasDatabaseName("fk_pc_idcompra_idx1");

                    b.HasIndex(new[] { "IdProveedorNit" }, "fk_pc_idproveedornit_idx");

                    b.ToTable("proveedor_compra", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Tratamiento", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("DetallesTratamiento")
                        .HasColumnType("text")
                        .HasColumnName("detalles_tratamiento");

                    b.Property<DateOnly?>("FechaEdicion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_edicion");

                    b.Property<int?>("IdDiagnostico")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_diagnostico");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("IdTratamiento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDiagnostico" }, "fk_t_iddiagnostico_idx");

                    b.ToTable("tratamiento", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("clave");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("IdPersona")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id_persona");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre_usuario");

                    b.HasKey("IdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPersona" }, "fk_u_idpersona_idx");

                    b.HasIndex(new[] { "NombreUsuario" }, "nombre_usuario_UNIQUE")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.UsuarioPerfil", b =>
                {
                    b.Property<int>("IdUsuarioperfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuarioperfil");

                    b.Property<int?>("IdPerfil")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_perfil");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdUsuarioperfil")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPerfil" }, "fk_up_idperfil_idx");

                    b.HasIndex(new[] { "IdUsuario" }, "fk_up_idusuario_idx");

                    b.ToTable("usuario_perfil", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.VentaPago", b =>
                {
                    b.Property<int>("IdVentapago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_ventapago");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IdMedioDePago")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_medio_de_pago");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_venta");

                    b.Property<float?>("Monto")
                        .HasColumnType("float")
                        .HasColumnName("monto");

                    b.HasKey("IdVentapago")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMedioDePago" }, "fk_vp_idmediodepago_idx");

                    b.HasIndex(new[] { "IdVenta" }, "fk_vp_idventa_idx");

                    b.ToTable("venta_pago", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Ventum", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_venta");

                    b.Property<float?>("Abono")
                        .HasColumnType("float")
                        .HasColumnName("abono");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<int?>("IdUsuarioempleado")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuarioempleado");

                    b.Property<int?>("IdUsuariopaciente")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuariopaciente");

                    b.Property<float?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.HasKey("IdVenta")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarioempleado" }, "fk_v_idusuarioempleado_idx");

                    b.HasIndex(new[] { "IdUsuariopaciente" }, "fk_v_idusuariopaciente_idx");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.VwHistoriaClinicaCompletum", b =>
                {
                    b.Property<string>("DetallesTratamiento")
                        .HasColumnType("text")
                        .HasColumnName("detalles_tratamiento");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text")
                        .HasColumnName("diagnostico");

                    b.Property<DateOnly?>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdHistoriaclinica")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_historiaclinica");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("primer_nombre");

                    b.ToTable((string)null);

                    b.ToView("vw_historia_clinica_completa", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.VwInventarioCompra", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_producto");

                    b.Property<string>("Nombre")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre");

                    b.Property<float?>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .HasColumnType("int(11)")
                        .HasColumnName("stock");

                    b.Property<decimal?>("TotalComprado")
                        .HasPrecision(32)
                        .HasColumnType("decimal(32)")
                        .HasColumnName("total_comprado");

                    b.Property<DateOnly?>("UltimaCompra")
                        .HasColumnType("date")
                        .HasColumnName("ultima_compra");

                    b.ToTable((string)null);

                    b.ToView("vw_inventario_compras", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.VwVentasDetallada", b =>
                {
                    b.Property<float?>("Abono")
                        .HasColumnType("float")
                        .HasColumnName("abono");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("apellido_cliente");

                    b.Property<string>("ApellidoEmpleado")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("apellido_empleado");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int(11)")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_venta");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("NombreEmpleado")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nombre_empleado");

                    b.Property<float?>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("precio");

                    b.Property<string>("Producto")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("producto");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("double")
                        .HasColumnName("subtotal");

                    b.Property<float?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.ToTable((string)null);

                    b.ToView("vw_ventas_detalladas", (string)null);
                });

            modelBuilder.Entity("Optica1.Models.Citas", b =>
                {
                    b.HasOne("Optica1.Models.Usuario", "IdUsuarioempleadoNavigation")
                        .WithMany("CitasIdUsuarioempleadoNavigations")
                        .HasForeignKey("IdUsuarioempleado")
                        .HasConstraintName("fk_c_idusuarioempleado");

                    b.HasOne("Optica1.Models.Usuario", "IdUsuariopacienteNavigation")
                        .WithMany("CitasIdUsuariopacienteNavigations")
                        .HasForeignKey("IdUsuariopaciente")
                        .HasConstraintName("fk_c_idusuariopaciente");

                    b.Navigation("IdUsuarioempleadoNavigation");

                    b.Navigation("IdUsuariopacienteNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Diagnostico", b =>
                {
                    b.HasOne("Optica1.Models.Historiaclinica", "IdHistoriaclinicaNavigation")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("IdHistoriaclinica")
                        .HasConstraintName("fk_d_idhistoriaclinica");

                    b.Navigation("IdHistoriaclinicaNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Producto", b =>
                {
                    b.HasOne("Optica1.Models.Proveedor", "IdProveedorNitNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedorNit")
                        .HasConstraintName("fk_producto_proveedor");

                    b.Navigation("IdProveedorNitNavigation");
                });

            modelBuilder.Entity("Optica1.Models.ProductoCompra", b =>
                {
                    b.HasOne("Optica1.Models.Compra", "IdCompraNavigation")
                        .WithMany("ProductoCompras")
                        .HasForeignKey("IdCompra")
                        .HasConstraintName("fk_pc_idcompra");

                    b.HasOne("Optica1.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoCompras")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("fk_pc_idproducto");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Optica1.Models.ProductoVentum", b =>
                {
                    b.HasOne("Optica1.Models.Producto", "IdProductoNavigation")
                        .WithMany("ProductoVenta")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("fk_pv_idproducto");

                    b.HasOne("Optica1.Models.Ventum", "IdVentaNavigation")
                        .WithMany("ProductoVenta")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("fk_pv_idventa");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Optica1.Models.ProveedorCompra", b =>
                {
                    b.HasOne("Optica1.Models.Compra", "IdCompraNavigation")
                        .WithMany("ProveedorCompras")
                        .HasForeignKey("IdCompra")
                        .HasConstraintName("fk_proveedorc_idcompra");

                    b.HasOne("Optica1.Models.Proveedor", "IdProveedorNitNavigation")
                        .WithMany("ProveedorCompras")
                        .HasForeignKey("IdProveedorNit")
                        .HasConstraintName("fk_proveedorc_idproveedornit");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdProveedorNitNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Tratamiento", b =>
                {
                    b.HasOne("Optica1.Models.Diagnostico", "IdDiagnosticoNavigation")
                        .WithMany("Tratamientos")
                        .HasForeignKey("IdDiagnostico")
                        .HasConstraintName("fk_t_iddiagnostico");

                    b.Navigation("IdDiagnosticoNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Usuario", b =>
                {
                    b.HasOne("Optica1.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPersona")
                        .HasConstraintName("fk_u_idpersona");

                    b.Navigation("IdPersonaNavigation");
                });

            modelBuilder.Entity("Optica1.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("Optica1.Models.Perfil", "IdPerfilNavigation")
                        .WithMany("UsuarioPerfils")
                        .HasForeignKey("IdPerfil")
                        .HasConstraintName("fk_up_idperfil");

                    b.HasOne("Optica1.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioPerfils")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("fk_up_idusuario");

                    b.Navigation("IdPerfilNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Optica1.Models.VentaPago", b =>
                {
                    b.HasOne("Optica1.Models.MedioDePago", "IdMedioDePagoNavigation")
                        .WithMany("VentaPagos")
                        .HasForeignKey("IdMedioDePago")
                        .HasConstraintName("fk_vp_idmediodepago");

                    b.HasOne("Optica1.Models.Ventum", "IdVentaNavigation")
                        .WithMany("VentaPagos")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("fk_vp_idventa");

                    b.Navigation("IdMedioDePagoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Ventum", b =>
                {
                    b.HasOne("Optica1.Models.Usuario", "IdUsuarioempleadoNavigation")
                        .WithMany("VentumIdUsuarioempleadoNavigations")
                        .HasForeignKey("IdUsuarioempleado")
                        .HasConstraintName("fk_v_idusuarioempleado");

                    b.HasOne("Optica1.Models.Usuario", "IdUsuariopacienteNavigation")
                        .WithMany("VentumIdUsuariopacienteNavigations")
                        .HasForeignKey("IdUsuariopaciente")
                        .HasConstraintName("fk_v_idusuariopaciente");

                    b.Navigation("IdUsuarioempleadoNavigation");

                    b.Navigation("IdUsuariopacienteNavigation");
                });

            modelBuilder.Entity("Optica1.Models.Compra", b =>
                {
                    b.Navigation("ProductoCompras");

                    b.Navigation("ProveedorCompras");
                });

            modelBuilder.Entity("Optica1.Models.Diagnostico", b =>
                {
                    b.Navigation("Tratamientos");
                });

            modelBuilder.Entity("Optica1.Models.Historiaclinica", b =>
                {
                    b.Navigation("Diagnosticos");
                });

            modelBuilder.Entity("Optica1.Models.MedioDePago", b =>
                {
                    b.Navigation("VentaPagos");
                });

            modelBuilder.Entity("Optica1.Models.Perfil", b =>
                {
                    b.Navigation("UsuarioPerfils");
                });

            modelBuilder.Entity("Optica1.Models.Persona", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Optica1.Models.Producto", b =>
                {
                    b.Navigation("ProductoCompras");

                    b.Navigation("ProductoVenta");
                });

            modelBuilder.Entity("Optica1.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("ProveedorCompras");
                });

            modelBuilder.Entity("Optica1.Models.Usuario", b =>
                {
                    b.Navigation("CitasIdUsuarioempleadoNavigations");

                    b.Navigation("CitasIdUsuariopacienteNavigations");

                    b.Navigation("UsuarioPerfils");

                    b.Navigation("VentumIdUsuarioempleadoNavigations");

                    b.Navigation("VentumIdUsuariopacienteNavigations");
                });

            modelBuilder.Entity("Optica1.Models.Ventum", b =>
                {
                    b.Navigation("ProductoVenta");

                    b.Navigation("VentaPagos");
                });
#pragma warning restore 612, 618
        }
    }
}
